// Generated by CoffeeScript 1.8.0
(function() {
  var ERROR, FLUSH_INTERVAL, INFO, LEVELS, LOG, NAME_TAG, ROTATION_INTERVAL, WARN;

  ERROR = 3;

  WARN = 2;

  INFO = 1;

  LOG = 0;

  LEVELS = ["log", "info", "warn", "error"];

  NAME_TAG = {
    "log": "LOG -",
    "info": "\u001b[32mINFO\u001b[0m -",
    "warn": "\u001b[33mWARNING\u001b[0m -",
    "error": "\u001b[31mERROR\u001b[0m -"
  };

  ROTATION_INTERVAL = 4 * 60 * 60 * 1000;

  FLUSH_INTERVAL = 5 * 1000;

  module.exports = {
    ERROR: ERROR,
    WARN: WARN,
    INFO: INFO,
    LOG: LOG,
    LEVELS: LEVELS,
    NAME_TAG: NAME_TAG,
    ROTATION_INTERVAL: ROTATION_INTERVAL,
    FLUSH_INTERVAL: FLUSH_INTERVAL,
    NOOP_FN: function() {}
  };

}).call(this);
